#!/usr/bin/env bash
# Display information about subdomains.

function digdomain {
	subdom="$1"
	fulldom="$1.$2"

	dig "$fulldom" | grep -A1 'ANSWER SECTION:' | awk '($0 ~ dom) {print "The subdomain " s " is a " $4 " record and points to " $5}' s="$subdom" dom="$fulldom"
}

if [ $# -eq 1 ]
then
	declare -a all_subdoms=( "www" "lb-01" "web-01" "web-02" )
	dom=$1
	for i in "${all_subdoms[@]}"
	do
		digdomain "$i" "$dom"
	done
else
	digdomain "$2" "$1"
fi
