#!/usr/bin/env bash
# Installs and configures nginx
apt-get update && apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
mv /var/www/html/index.nginx-debian.html /var/www/html/index.html
service nginx restart
