#!/usr/bin/env bash
# Print bad luck on the 4th iteration and good luck on the 8th
i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo 'bad luck'
	elif ((i == 8))
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	((i++))
done
