#!/usr/bin/env bash
# Resolves localhost to 127.0.0.2
# Resolves Facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ s/157.240.11.35/8.8.8.8/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
# cp /etc/hosts ~/hosts.new
# sed -i s/157.240.11.35/8.8.8.8/  ~/hosts.new
# cp -f ~/hosts.new /etc/hosts
